apiVersion: v1
kind: Service
metadata:
  name: ${{ secrets.APPSERVICE }}
  namespace: ${{ secrets.APPNAMESPACE }}
  labels:
    app: ${{ secrets.APPNAME }}
spec:
  selector:
    app: ${{ secrets.APPNAME }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ secrets.APPDEPLOYMENT }}
  namespace: ${{ secrets.APPNAMESPACE }}
  labels:
    app: ${{ secrets.APPNAME }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ${{ secrets.APPNAME }}
  template:
    metadata:
      labels:
        app: ${{ secrets.APPNAME }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
        - name: storemanager-api
          image: APPIMAGE
          ports:
            - containerPort: 5000
      # - name: nginx
      #   image: public.ecr.aws/z9d2n7e1/nginx:1.19.5
      #   ports:
      #   - containerPort: 80